[phases.install-frontend]
workingDirectory = "frontend"
cmds = ["npm install"]

[phases.build-frontend]
workingDirectory = "frontend"
cmds = ["npm run build"]

[phases.install-backend]
workingDirectory = "backend"
cmds = ["npm install"]

[phases.copy-frontend]
workingDirectory = "frontend"
cmds = ["cp -r dist ../backend/public"]

[start]
cmd = "node backend/index.js"
