[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install-frontend]
workingDirectory = "frontend"
cmds = ["npm install"]

[phases.build-frontend]
workingDirectory = "frontend"
cmds = ["npm run build"]

[phases.install-backend]
workingDirectory = "backend"
cmds = ["npm install"]

[start]
cmd = "concurrently \"cd frontend && npm run dev\" \"cd backend && npm run dev\""
